export const groups = [
  'Blossom World Society',
  'Coastal Natives',
  'Conservation IG',
  'Green & Clean',
  'Green Interest Group',
  'Green Nudge',
  'Green Print',
  'Guardians of Mother Earth',
  'Habitat for Humanity',
  'Hewlett Packard Enterprise',
  'International Coastal Cleanup',
  'IPP Financial Advisers',
  'Just One Earth',
  'Kindred Community',
  'Lions Club',
  'Little Green Men',
  'National Environment Agency',
  'National Parks',
  'Nature Society',
  'NUS Save',
  'NYP Geo Council',
  'One Planet',
  'Our Singapore Reefs',
  'Partoir',
  'Passion Wave',
  'Plastic-Lite',
  'Pulau Ubin Cleanup',
  'Restroom Association',
  'Secondsguru',
  'Seven Clean Seas',
  'SG Beach Warriors',
  'Shinnyo-en',
  'Singapore Kindness Movement',
  'The Singapore Glove Project',
  'The Singapore Scout Association',
  'Trash Hero',
  'Tzu Chi Foundation',
  'Waterways Watch Society',
  'Youth Corps',
  'Zero Waste SG',
]
